sudo: required

language: ruby
rvm:
  - 2.6.1

cache: bundler

addons:
  apt:
    sources:
      - chef-stable-xenial
    packages:
      - chefdk
  #artifacts: true

before_install:
    - gem update --system
    - gem install bundler
    
# Don't `bundle install` which takes about 1.5 mins
install:

services: docker

env:
  matrix:
  - INSTANCE=default-ubuntu-1604

before_script:
  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
  - eval "$(chef shell-init bash)"
  - gem install bundler
  - bundle update --bundler
  - chef --version
  - cookstyle --version
  - foodcritic --version

script: CHEF_LICENSE=accept-no-persist KITCHEN_LOCAL_YAML=kitchen.dokken.yml CHEF_VERSION=${CHEF_VERSION} kitchen verify ${INSTANCE}

matrix:
  include:
    - script:
      - chef exec delivery local all
      env: UNIT_AND_LINT=1
