sudo: required

# blocklist
#branches:
#  except:
#  - development

# safelist
#branches:
#  only:
#  - master
#  - stable

language: ruby
rvm:
  - 2.6.1

cache: bundler

addons:
  apt:
    sources:
      - chef-stable-xenial
    packages:
      - chef-workstation
  #artifacts: true

# Don't `bundle install` which takes about 1.5 mins
install:

services: docker

env:
  matrix:
  - INSTANCE=default-ubuntu-1604

before_script:
  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
  - eval "$(chef shell-init bash)"
  - gem install bundler:2.0.1
  - gem install inspec_tools
  - inspec --version
  - CHEF_LICENSE=accept chef gem update inspec
  - CHEF_LICENSE=accept chef gem update inspec-bin
  - inspec --version
  - bundle update --bundler
  - bundle install
  - chef --version
  - cookstyle --version
  - foodcritic --version

script: 
  - CHEF_LICENSE=accept-no-persist KITCHEN_LOCAL_YAML=kitchen.dokken.yml CHEF_VERSION=${CHEF_VERSION} kitchen verify ${INSTANCE} || true
  - export RESULTS=$(ls results/*.json)
  - inspec_tools compliance -j $RESULTS -f threshold.yml
